name: Test action
on:
  push:
    branches:
      - main
jobs:
  test:
    name: "Operous ssh test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - name: Run Operous ssh test
        uses: ./
        with:
          accountToken: ${{ secrets.OPEROUS_ACCOUNT_TOKEN }}
          instanceName: ${{ secrets.OPEROUS_ACCOUNT_INSTANCE }}
